site_name: Ambiente de Trilha de Dados
theme:
  name: material
  docs_dir: docs
  language: pt-BR
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.footer
    - navigation.indexes
    - navigation.tabs
    - search.highlight
    - search.share
    - search.suggest
  plugins:
    - typeset
    - search
  palette:
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/weather-sunny
        name: Modo claro
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Modo noturno
nav:
  - Home: 
    - Introdução: index.md
    - Como se organizar para os estudos: home/como_organizar_estudos.md
      - A importância da Segurança e Privacidade de dados: alfabetizacao-de-dados/05-governanca-dados/seguranca_dados.md
    - Conclusão:
      - Conclusão: alfabetizacao-de-dados/conclusao.md
