site_name: Ambiente de Trilha de Dados
theme:
  name: material
  docs_dir: docs
  language: pt-BR
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.footer
    - navigation.indexes
    - navigation.tabs
    - search.highlight
    - search.share
    - search.suggest
  plugins:
    - typeset
    - search
  palette:
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/weather-sunny
        name: Modo claro
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Modo noturno
nav:
  - Home: 
    - Introdução: index.md
    - Como se organizar para os estudos: home/como_organizar_estudos.md
  - Trilha de Alfabetização de Dados:
    - Home: alfabetizacao-de-dados/introducao.md
    - Alfabetizacao de Dados:
      - O que é a alfabetizacao de Dados: alfabetizacao-de-dados/00-o-que-e-alfabetizacao/o_que_e_alfabetizacao.md
      - Cultura Data Driven: alfabetizacao-de-dados/00-o-que-e-alfabetizacao/cultura_data_driven.md
    - O Profissional de Dados e suas Ferramentas:
      - Conheça os profissionais e suas ferramentas: alfabetizacao-de-dados/01-profissionais-suas-ferramentas/profissionais_suas_ferramentas.md
      - O Power BI: alfabetizacao-de-dados/01-profissionais-suas-ferramentas/powerbi_ferramenta.md
    - Gestão de Indicadores:
      - Entendendo Metas e Indicadores: alfabetizacao-de-dados/02-gestao-indicadores/ler_interpretar_dados.md
      - Entendendo os Tipos de Dados e Dashboard: alfabetizacao-de-dados/02-gestao-indicadores/diferenca_dash_relatorio.md
      - Conceito de Dados Estruturados e Não-Estruturados: alfabetizacao-de-dados/02-gestao-indicadores/dados_estruturados.md
    - Storytelling com Dados:
        - O que é Storytelling com Dados: alfabetizacao-de-dados/03-storytelling/storytelling_dados.md
    - Análises Avançadas de Dados:
        - Técnicas de Análises: alfabetizacao-de-dados/04-analises-avancadas/tecnicas_avancadas_dados.md
        - Ciência de Dados: alfabetizacao-de-dados/04-analises-avancadas/ciencia_de_dados.md
    - Governança de Dados:
      - O que é a Governança de Dados: alfabetizacao-de-dados/05-governanca-dados/o_que_governanca.md
      - Data Steward e Data Owner: alfabetizacao-de-dados/05-governanca-dados/papeis_ferramentas.md
      - A Importância da Qualidade dos Dados: alfabetizacao-de-dados/05-governanca-dados/qualidade_dados.md
      - A importância da Segurança e Privacidade de dados: alfabetizacao-de-dados/05-governanca-dados/seguranca_dados.md
    - Conclusão:
      - Conclusão: alfabetizacao-de-dados/conclusao.md
